server:
  port: 80
#不配置datasource,数据库操作由jdbc实现
logging:
  level:
    com:
      example:
        mapper : debug
dubbo:
  application:
    name: wmsUserServiceProvider
  registry:
    address: 116.196.81.197:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.haveFun