server:
  port: 9000
#配置datasource,数据库操作由JPA实现
spring:
  datasource:
    driverClassName : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/meituan?useUnicode=true&amp;characterEncoding=utf8
    username : meituan
    password : --Summer.911
    hikari:
      max-lifetime: 120000
  jpa:
    hibernate :
      ddl-auto : update
    database-platform: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    com:
      example:
        mapper : debug
dubbo:
  application:
    name: wmsUserServiceProvider
    qos:
      enable: true
      port: 44444
      accept:
        foreign:
          ip: false
  registry:
    address: 116.196.81.197:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.haveFun